#!/usr/bin/env bash
# Benchmark harness (DESIGN.md §9). Measures exec latency (ELF vs SELF memfd
# vs SELF native) and file sizes. Writes bench/results.md. Run in `nix develop`.
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
export PYTHONPATH="$repo"
SELF_EXEC="$repo/loader/self-exec"
out="$repo/bench/results.md"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cd "$work"

make -C "$repo/loader" >/dev/null

# subjects: a tiny hello and a real coreutils binary
cat > hello.c <<'EOF'
#include <stdio.h>
int main(void){ puts("Hello, world!"); return 0; }
EOF
cc -O2 hello.c -o hello
# noop: minimal dynamic PIE, exits 0 -- isolates raw exec/link cost
cat > noop.c <<'EOF'
int main(void){ return 0; }
EOF
cc -O2 noop.c -o noop

# --shell=none: these run in a few ms, below hyperfine's shell-calibration
# floor; `env` is a real binary so VAR=val prefixes still work under -N.
hyperfine_json() { hyperfine -N --warmup 30 --min-runs 300 --export-json "$2" "$1" >/dev/null; }
mean_ms() { python3 -c "import json,sys;print(f\"{json.load(open('$1'))['results'][0]['mean']*1000:.3f}\")"; }

{
  echo "# SELF benchmarks"
  echo
  echo "Generated by \`bench/run.sh\`. Host: \`$(uname -mrs)\`."
  echo "hyperfine -N warmup=30 min-runs=300; times are mean wall-clock per exec."
  echo
  echo "## Exec latency"
  echo
  printf '| subject | ELF | SELF memfd (M1) | SELF native (M2) | memfd/ELF | native/ELF |\n'
  printf '|---|--:|--:|--:|--:|--:|\n'
} > "$out"

for subj in hello noop; do
  python -m selfconv elf2self "$subj" "$subj.self" >/dev/null 2>&1
  hyperfine_json "$work/$subj"                                       elf.json
  hyperfine_json "env SELF_MODE=memfd  $SELF_EXEC $work/$subj.self"  memfd.json
  hyperfine_json "env SELF_MODE=native $SELF_EXEC $work/$subj.self"  native.json
  e=$(mean_ms elf.json); m=$(mean_ms memfd.json); n=$(mean_ms native.json)
  rm=$(python3 -c "print(f'{$m/$e:.2f}x')"); rn=$(python3 -c "print(f'{$n/$e:.2f}x')")
  printf '| %s | %s ms | %s ms | %s ms | %s | %s |\n' "$subj" "$e" "$m" "$n" "$rm" "$rn" >> "$out"
done

# ── file sizes ───────────────────────────────────────────────────────
{
  echo
  echo "## File size"
  echo
  printf '| subject | ELF | SELF (full) | SELF (stripped) |\n'
  printf '|---|--:|--:|--:|\n'
} >> "$out"

for subj in hello "$(readlink -f "$(type -P ls)")"; do
  name=$(basename "$subj")
  python -m selfconv elf2self "$subj" "$name.full.self" >/dev/null 2>&1
  cp "$name.full.self" "$name.strip.self"
  sqlite3 "$name.strip.self" "DELETE FROM sections; DELETE FROM notes; DELETE FROM symbols WHERE source='symtab'; VACUUM;"
  e=$(stat -c%s "$subj"); f=$(stat -c%s "$name.full.self"); s=$(stat -c%s "$name.strip.self")
  printf '| %s | %s B | %s B | %s B |\n' "$name" "$e" "$f" "$s" >> "$out"
done

{
  echo
  echo "## Notes"
  echo
  echo "- **memfd (M1)** pays for reconstructing the ELF into a memfd plus a"
  echo "  second execve; it is the honest worst case and still a small"
  echo "  constant over a bare exec."
  echo "- **native (M2)** maps segments directly and hands off to ld.so,"
  echo "  avoiding the second execve; it trades that for doing ld.so's"
  echo "  bookkeeping in userspace."
  echo "- Neither mode shares text pages across processes the way a normal"
  echo "  ELF mapping does (DESIGN §8, §9): the segment blobs are copied, not"
  echo "  mapped, because SQLite overflow pages are not page-aligned."
  echo "- SELF file size carries SQLite's b-tree overhead but makes stripping"
  echo "  a transaction (\`DELETE\`+\`VACUUM\`) rather than offset surgery."
} >> "$out"

echo "wrote $out"
cat "$out"
